---
title: "Slike"
author: "Roman Luštrik"
date: "05 februar 2017"
output: html_document
---

```{r}
library(ggplot2)
library(MASS)
```

Individual with marginal densities.
```{r}
set.seed(357)
df <- data.frame(x = rnorm(1000, 0, 10), y = rnorm(1000, 0, 10))

p <- ggplot(df, aes(x, y)) + 
  geom_point(alpha = 0.5, size = 2) + 
  theme_bw() +
  scale_x_continuous(limits = c(-40, 40)) +
  scale_y_continuous(limits = c(-40, 40)) +
  geom_point(x = 0, y = 0, size = 3, color = "blue") +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        aspect.ratio = 1)

png("./figures/homerange_usage.png", width = 500, height = 500, units = "px")
ggExtra::ggMarginal(p, type = "density")
dev.off()
```

Kernels for three examples
```{r}
set.seed(2)

nind <- 3
xy <- data.frame(xc = c(0, 5, -2),
                 yc = c(0, 0, 6))

# draw circle
radius <- 5
theta <- seq(0, 2 * pi, length = 200)
crc <- data.frame(x = radius * cos(theta), y = radius * sin(theta))

N <- 100
pts <- apply(xy, MARGIN = 1, FUN = function(m, SD) {
  out <- data.frame(x = rnorm(N, mean = m["xc"], sd = SD),
                    y = rnorm(N, mean = m["yc"], sd = SD))
  out
}, SD = 1)
pts <- do.call(rbind, pts)

ggplot(pts, aes(x = x, y = y)) +
  theme_bw() +
  scale_x_continuous(limits = c(-9, 11)) +
  scale_y_continuous(limits = c(-8, 12)) +
  geom_path(data = crc, aes(x = x, y = y)) +
  geom_density_2d() +
  geom_point(alpha = 0.4, size = 1) +
  geom_point(data = xy, aes(x = xc, y = yc), color = "blue", size = 3) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        aspect.ratio = 1)

ggsave("./figures/kernels_hr.png", width = 5, height = 5)
```

```{r}
ggplot(pts, aes(x = x, y = y)) +
  theme_bw() +
  scale_x_continuous(limits = c(-9, 11)) +
  scale_y_continuous(limits = c(-8, 12)) +
  geom_polygon(data = crc, aes(x = x, y = y), color = "grey", alpha = 0.25) +
  geom_path(data = crc, aes(x = x, y = y)) +
  geom_density_2d() +
  geom_point(alpha = 0.4, size = 1) +
  geom_point(data = xy, aes(x = xc, y = yc), color = "blue", size = 3) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        aspect.ratio = 1)

ggsave("./figures/kernels_hr_colored.png", width = 5, height = 5)
```

Padanje verjetnosti ulovljivosti.
```{r}
hn <- function(x, sigma) exp(-(x^2)/(2 * sigma^2)) # hn = half normal
x <- seq(from = 0, to = 8, by = 0.2)
xy <- data.frame(x = x, y = hn(x = x, sigma = 2))

ggplot(xy, aes(x = x, y = y)) +
  theme_bw() +
  geom_line() +
  ylab("Verjetnost ulovljivosti") +
  xlab("Oddaljenost od centroida") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggsave("./figures/half_normal.png", width = 4, height = 3)
```


```{r}

```

